[project]
name = "feedix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.12",
    "fr-core-news-sm>=3.8.0",
    "jinja2>=3.1.6",
    "requests>=2.32.5",
    "spacy>=3.8.11",
    "uuid7>=0.1.0",
]
